repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.0
    hooks:
      # Run the linter on changed files only
      - id: ruff
        args: [--fix]
      # Run the formatter on changed files only
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.0
    hooks:
      - id: mypy
        args: [--strict]
        files: ^bot/
        additional_dependencies:
          - discord.py~=2.6.0
          - pydantic~=2.10
          - pydantic-settings~=2.8
          - requests~=2.31
          - types-requests>=2.32.4.20250913